server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/bns
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

keycloak.realm=projet
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=projet-client
keycloak.public-client=true
keycloak.ssl-required=external
keycloak.bearer-only=true
spring.application.name=backendprojet





spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/projet
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/projet/protocol/openid-connect/certs