server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/bns
spring.datasource.username=postgres
spring.datasource.password=123456789
# ?? Keycloak Admin ??????????????????????????????
keycloak.server-url=http://localhost:8080

keycloak.admin-realm=projet
keycloak.client-id=projet-client
keycloak.client-secret=JPxawKadfqFXsx7XwqL0RyjLzNPZw1he
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Camunda
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Sabrina
# Camunda
# ? Désactiver la validation stricte du History TTL
camunda.bpm.generic-properties.properties.historyTimeToLive=180
camunda.bpm.webapp.index-redirect-enabled=true
camunda.bpm.filter.create=All tasks
camunda.bpm.history-time-to-live=180

keycloak.realm=projet
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=projet-client
keycloak.public-client=true
keycloak.ssl-required=external
keycloak.bearer-only=true
spring.application.name=backendprojet





spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/projet
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/projet/protocol/openid-connect/certs